### ISSUE TITLE
Change 'then' to 'than'

### ISSUE THREAD

**Issue by saulens22** [danielme85/laravel-log-to-db#13]
There are two methods with typo in them: 'removeOldestIfMoreThen' and 'removeOlderThen'. 'Then' should be replaced by 'Than' to be correct English sentence. Or, at least, this issue should stay here to inform others about this potential issue in otherwise great package.

**Comment by danielme85** [comment]
For some reason I get those mixed up all the time. As you might have guessed: english is not my first language but it should be at this point.

It's one thing to have weird language in the readme, but in the actually function name is too far! I'll fix it, then that's that.

Thanks for the heads-up!

**Comment by saulens22** [comment]
Well, at least it's consistent. Copying function name from readme works OK. I guess I'm first who typed it lol.

Also, have in mind that changing function name might be breaking functionality for some users.

**Comment by danielme85** [comment]
Yeah I'll add some function wrappers with the "alternative" spelling and change the readme to reference the correct spelling into the dev-branch for now. That way it can be added with any other future improvements/changes/fixes, and it would support cases with the wrong spelling.

Don't want to give people issues with breaking changes because of some silly spelling on my end, but I can see how it might hurt your brain when you type it :p

**Comment by danielme85** [comment]
Actually found couple of bugs #14  when looking into this, so thanks again!
Both correct and wrong spelling should work in newest release and dev-master now #15

**Comment by saulens22** [comment]
Thank you for quick reaction. Everything works great!
