### ISSUE TITLE
Duplicate values ​​in the log

### ISSUE THREAD

**Issue by Aymenel** [danielme85/laravel-log-to-db#9]
Hello. Please tell me for what purpose intended field `extra`?
I have all the records contain only one text "{"file":"/home/vagrant/ay-tech/vendor/laravel/framework/src/Illuminate/Log/Logger.php","line":176,"class":"Illuminate\Log\Logger","function":"writeLog"}"
Maybe I'm doing something wrong?

I use Laravel v6

**Comment by danielme85** [comment]
Hi, good question.
This was actually a request (https://github.com/danielme85/laravel-log-to-db/issues/5) to have the introspection processor present. 
This process just tracks what function/class/file is calling the write log function.

This does make little (to no) sense to have on per default, because for the intended use of this package with the Laravel logger, this extra field will always be the same! Sorry about that.

Thank you for bringing this to my attention, I did not spend enough time thinking this through.
When I have some time I will change this to be optional in the configs. I might also add support for all other processors: https://github.com/Seldaek/monolog/tree/master/src/Monolog/Processor
I think they all add extra information... in 'extra' 😉

**Comment by danielme85** [comment]
The master branch have these processors as optional config now. Should no more useless spam in 'extra' (unless you want to have that). 
Let me know if I broke it 🙃

**Comment by Aymenel** [comment]
Very quickly, thank you.
I will try to check in the next couple of days:)

**Comment by danielme85** [comment]
Should no longer be an issue in dev-master and latest release since: f5a5ed7b4d5efafc15f9b39357636314646708ec
